### PR TITLE
Fixed missing point.

### PR DESCRIPTION
**Pull request by karan919**
In my last PR, I forgot to put one point. I tried to make the readme.md easy to understand.

### CODE REVIEW

**Comment by tminussi** [comment]
And you certainly did. This PR  however, is not good. The line you are removing should stay because those parameters are completely optional

**Comment by karan919** [comment]
The line I removed (npm run local) is put on the second point of how to run because I forget to put that point. And without running the server, the app won't work. I tried to make How to run section easy to understand, so that people who just want to run the app, won't have to look much.

**Comment by tminussi** [comment]
Thanks, @karan919. Can you please resolve the conflicts before I can merge your code in?

**Comment by karan919** [comment]
Resolved the conflict. :+1:

**Pull request merged**
