### PR TITLE
Intergrate bundeler

### PR DESCRIPTION
**Pull request by JipSterk**
Impelements #8

### CODE REVIEW

**Comment by tminussi** [comment]
@JipSterk can you please modify the README.md accordingly as well as adding yourself to contributors.json?

Great job there! Thanks!

**Comment by JipSterk** [comment]
@tminussi as requested i added myself to the contributors.json
#2 shouldn't be a problem now. 
As soon as this is merged i will start working on that issue.

**Comment by tminussi** [comment]
Thanks, @JipSterk!

**Comment by tminussi** [comment]
@JipSterk I looked into the merge request and everything apparently was fine, but it does not work anymore. No CSS nor JS files are being loaded. Also, when I run npm start:dev I get an error and it simply does not work.

Can you please check the cause of the regression?

Thanks!

**Comment by tminussi** [comment]
I have reverted your merge temporarily until the issue is fixed

Thanks!

**Pull request merged**
