### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by chgasparoto**
It's related to issue #5

### CODE REVIEW

**Comment by chgasparoto** [comment]
`> jest "--coverage"

 PASS  __tests__/index.js
  Github service - fetchPullRequests
    ✓ should reject the request if status code >= 400 (22ms)
    ✓ should return zero if no PR were made yet (45ms)
    ✓ should return an object with valid PRs data (117ms)
    ✓ should return an object with no valid PRs data (85ms)
  createMessage
    ✓ should return a message if quantity is 0 (15ms)
    ✓ should return a message if quantity is between 1 and 3 (16ms)
    ✓ should return a message if quantity is 4 (16ms)
    ✓ should return a message if quantity is >= 5 (15ms)

--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------|----------|----------|----------|----------|-------------------|
All files           |      100 |      100 |      100 |      100 |                   |
 server             |      100 |      100 |      100 |      100 |                   |
  testSetup.js      |      100 |      100 |      100 |      100 |                   |
 server/service     |      100 |      100 |      100 |      100 |                   |
  github-service.js |      100 |      100 |      100 |      100 |                   |
--------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        1.455s
Ran all test suites.`

**Comment by chgasparoto** [comment]
selection_026

**Comment by chgasparoto** [comment]
@tminussi done!
I'm glad you liked it :)

**Comment by tminussi** [comment]
I certainly did! Did not have time to review the code yet but I can judge by the name of the tests that you know what you're doing. I'll review it tomorrow when I grab my computer and will then review.

Thanks again!

**Pull request merged**
