### PR TITLE
Add integration tests using cypress

### PR DESCRIPTION
**Pull request by ypahalajani**
Addresses #6 (Add integration tests)

Test cases added for error-handling on UI - in case of error from XHR request, **assert** that **loader is not visible** and **a proper error message in displayed** to user.

### CODE REVIEW

**Comment by tminussi** [comment]
@ypahalajani quite an amazing work you did here! Thanks!

Can you just please update the README.md file and add yourself to contributors.json?

**Comment by ypahalajani** [comment]
@tminussi I have updated this PR. You can review it now.

There are a lot of files which are examples in the **cypress/examples** folder. You can skip them(because, their purpose is to refer them, offline, for writing test cases). The only file that must be reviewed, in that folder, is **error_spec.js**(which contains the actual test assertions).

**Comment by tminussi** [comment]
Great job, @ypahalajani.

Thanks! Your PR has been merged in successfully!

**Comment by ypahalajani** [comment]
@tminussi I saw - you had to revert many PRs. Let me know if something goes wrong.

**Comment by tminussi** [comment]
yes, @ypahalajani. Unfortunately :( I ran a quick check and I think your code was not affected by the reverts. I will check it for real when I have some time tonight and I will let you know. Thanks for your help!

**Pull request merged**
